### ISSUE TITLE
crowdstrike API script

### ISSUE THREAD

**Issue by warezers** [tyler-tee/CrowdClient#2]
I am trying to use python script crowdstrike module to check all malicious domain and ip details, SHA256

I have a list of domains and IP addresses, so how do I test malicious status or not with crowdstrike API using script
I used this crowdstrike module but got no json response and it just shows an empty list and none

I already followed the docs to create a secret API id and client id and also selected the api scope, but still no response

the authentication token is successful

do i need to do something ?

```
from CrowdClient.crowdclient import CrowdClient
client_id='id'
client_secret='secret' 
falcon_client = CrowdClient(client_id, client_secret,'https://api.us-2.crowdstrike.com')
falcon_client.authenticate()
host_count = falcon_client.indicator_upload(['26147561abf4614ee049f859cad9228b5346e32f81e3ed04616abc308a353124'],'sha256')
print(host_count)
host_count1 = falcon_client.indicator_info('26147561abf4614ee049f859cad9228b5346e32f81e3ed04616abc308a353124','sha256')
print(host_count1)
```

Result:

```
None
[]
```

**Comment by tyler-tee** [comment]
Hey, I apologize for the extreme delay. CrowdStrike had deprecated several of their IOC endpoints - I've updated the respective methods with the new versions.
